language: php
php:
  - '7.1'
services:
  - docker
before_script:
  - docker-compose build
script:
  - docker-compose run application composer test
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
notifications:
    on_success: never
    on_failure: always