version: "2"

services:
  application:
    build:
      context: application
      args:
        - CODE_ENV=dev
    environment:
      - CODE_ENV=dev
    image: php-cli-composer
    container_name: application_loadsmart
